### ISSUE TITLE
[FEATURE]: user 삭제시 관련 데이터 보관 처리 및 복구

### ISSUE THREAD

**Issue by jessie129j** [bmrdevteam/school-information-system#62]
# Description
userId가 user01인 유저를 삭제했을 때 관련 데이터를 삭제하지 않아 userId가 user01인 유저를 다시 생성했을 때 userId==user01인 데이터를 그대로 가져오는 문제가 있음

**관련 데이터**
- user
- archive
- registrations
- notifications
- syllabuses (작성한 수강계획서)
- enrollments (신청한 수업)

# Todo
- [ ] 보관된 데이터 저장할 db 생성
- [ ] user 삭제시 관련 데이터 보관 기능 개발
- [ ] user 복구 기능 개발
- [ ] 관련 페이지 생성

**Comment by jessie129j** [comment]
user 삭제시 관련 데이터 보관하는 방식으로 해결하려 했으나 연결된 데이터를 읽고 쓰는 과정에서 관련 데이터에 충돌이 일어날 가능성이 높아보임. user(oid)를 적용하는 방식으로 해결하려 함.

**Comment by devgoodway** [comment]
내 생각에도 object id로 특정하는 것이 좋을 것 같아
